<?php
/** @var $this LikeTrelloPriority */
layout_page_header('Like Trello');
layout_page_begin();
?>
<link rel="stylesheet" type="text/css" href="<?= plugin_file('trello.css')?>"/>

<form>
	<input type="hidden" name="page" value="<?= $this->selfLink ?>" />
	<label>Severity:
		<select name="severity">
			<option></option>
			<?php
			$this->print_enum_string_option_list_with_count( 'severity', $this->severity );
			?>
		</select>
	</label>
	<label>Assigned:
		<select name="handler">
			<option></option>
			<?php print_assign_to_option_list(
				$this->handler,
				helper_get_current_project()
			);
			?>
		</select>
	</label>
	<input type="submit" value="Filter" />
</form>

<div class="trello ui-helper-clearfix" id="reloadTarget"
	 data-href="<?= $this->selfLink ?>">
	<?= $this->renderLists(); ?>
</div>

<a class="btn-floating btn-large waves-effect waves-light"
style="bottom: 45px; right: 24px;">
	<i class="fa fa-pencil"></i>
</a>

<form id="add-issue">
	<input type="hidden" name="page" value="<?= $this->selfLink?>" />
	<input type="hidden" name="action" value="addIssue" />
	<textarea name="summary" placeholder="Summary"
			  style="width: 100%" rows="10"
	></textarea>
<!--	<input type="submit" value="Submit" />-->
</form>

<script src="<?php echo plugin_file( 'trello.js' ) ?>"></script>
<?php
layout_page_end();
?>
