<?php html_page_top('Like Trello'); ?>
<link rel="stylesheet" type="text/css" href="<?= plugin_file('trello.css')?>"/>

<form>
	<input type="hidden" name="page" value="LikeTrello/trello" />
	<label>Severity
		<select name="severity">
			<option></option>
			<?php print_enum_string_option_list( 'severity', $this->severity ); ?>
		</select>
	</label>
	<input type="submit" value="Filter" />
</form>

<div class="trello ui-helper-clearfix" id="reloadTarget">
	<?= $this->renderLists(); ?>
</div>

<script src="<?php echo plugin_file( 'trello.js' ) ?>"></script>
<?php html_page_bottom(); ?>
